@startuml Fluxo de envio da contagem agendada
title Fluxo de envio da contagem agendada
  participant "Zatanna" #8698C0
  participant "Darkseid Api" #193464  

  alt criar nova contagem em branco para o estoquista
    "Zatanna" -> "Darkseid Api": GET /v1/organizations/{id}/scheduled_countings?counting_status.slug=”scheduled”
    "Darkseid Api" -> "Zatanna": http status 200
    "Darkseid Api" -> "Darkseid Api": verifica se a contagem esta \nprogramada para o próximo dia
    "Zatanna" -> "Darkseid Api": GET /v1/organizations/{id}/counting_status
    "Darkseid Api" -> "Zatanna": retorna todos os status de contagem disponíveis
    "Zatanna" -> "Darkseid Api": PATCH /v1/organizations/{id}/scheduled_countings/{id}
    "Darkseid Api" -> "Zatanna": http status 200
    "Zatanna" -> "Darkseid Api": POST /v1/organizations/{id}/branches/{id}/scheduled_countings/{id}/countings
    "Darkseid Api" -> "Zatanna": http status 201
  end
@enduml