@startuml Fluxo de inativação da contagem passada
title Fluxo de inativação da contagem passada
  participant "Zatanna" #8698C0
  participant "Darkseid Api" #193464  

  alt deletar agendamento de contagem passada
    "Zatanna" -> "Darkseid Api": GET v2/organizations/${organization}/scheduled_countings?status=tostart
    "Darkseid Api" -> "Zatanna": http status 200    
    note right: 00-EPC102-lista-de-contagens-progamadas.json
    "Zatanna" -> "Zatanna": verifica quais agendamentos de contagem que já \nvenceram o prazo e não foram finalizadas
    "Zatanna" -> "Darkseid Api": PATCH v2/organizations/${organization}/scheduled_countings/{$id}/status
    "Darkseid Api" -> "Zatanna": http status 201    
  end
  
  alt deletar contagem passada
    "Zatanna" -> "Darkseid Api": GET v2/organizations/${organization}/branches/{$branch_id}/countings?status=tostart
    "Darkseid Api" -> "Zatanna": http status 200
    "Zatanna" -> "Darkseid Api": GET v2/organizations/${organization}/branches/{$branch_id}/countings?status=started
    "Darkseid Api" -> "Zatanna": http status 200
    "Zatanna" -> "Zatanna": verifica quais contagens que já \nvenceram o prazo e não foram finalizadas
    "Zatanna" -> "Darkseid Api": PATCH v2/organizations/${organization}/branches/{$branch_id}/countings/{id}
    "Darkseid Api" -> "Zatanna": http status 201
  end 
@enduml