version: '3'

services:
  delivery:
    image: postgres:16-alpine3.19
    container_name: postgres_delivery-api
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=delivery-db
  sonarqube:
    image: sonarqube
    container_name: sonarqube_delivery-api
    restart: unless-stopped
    expose:
      - 9000
    ports:
      - "0.0.0.0:9000:9000"