version: '3'

services:
  api:
    build: .
    container_name: delivery-api
    restart: always
    tty: true
    ports: 
       - 9000:9000
    networks:
      - compose-bridge
    depends_on:
       - postgres

  postgres:
    image: postgres:16-alpine3.19
    container_name: postgres_delivery-api
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=delivery-db
    networks:
      - compose-bridge
    volumes:
      - ./postgres:/var/lib/postgres

  sonarqube:
    image: sonarqube
    container_name: sonarqube_delivery-api
    restart: always
    tty: true
    ports:
      - "0.0.0.0:9002:9000"

networks:
  compose-bridge:
    driver: bridge