@startuml Fluxo de apuração das divergências
title Fluxo de apuração das divergências

  actor "estoquista"
  participant "Catwoman App" #193464  
  participant "Catwoman Api" #193464
  participant "Darkseid Api" #193464  
  participant "Eddie" #8698C0

  alt "Estoquista finaliza a contagem"
    "estoquista" -> "Catwoman App": Finaliza contagem tocando no botão "Finalizar e gerar divergências"
    "Catwoman App" -> "Catwoman Api": PATCH /v1/organizations/{id}/branches/{id}/countings/{id}
    "Catwoman Api" -> "Darkseid Api": PATCH /v1/organizations/{id}/branches/{id}/countings/{id}
    "Darkseid Api" -> "Catwoman Api": https status 200
    "Catwoman Api" -> "Catwoman App": https status 200
    "estoquista" -> "Catwoman App": Deseja visualizar o resumo das divergências
    "Catwoman App" -> "Catwoman Api": GET /v1/organizations/{id}/branches/{id}/countings/{id}/divergences
    "Catwoman Api" -> "Darkseid Api": GET /v1/organizations/{id}/branches/{id}/countings/{id}/counting_summaries?expand=true
    "Darkseid Api" -> "Catwoman Api": https status 200
    "Catwoman Api" -> "Catwoman App": https status 200
  end

  alt "Estoquista reconta e salva as divergências"
    "estoquista" -> "Catwoman App": Estoquista informa a nova quantidade
    "Catwoman App" -> "Catwoman Api": PATCH /v1/organizations/{id}/branches/{id}/countings/{id}/divergences/{id}
    "Catwoman Api" -> "Darkseid Api": PATCH /v1/organizations/{id}/branches/{id}/countings/{id}/counting_summaries/{id}
    "Darkseid Api" -> "Catwoman Api": https status 200
    "Catwoman Api" -> "Catwoman App": https status 200
    "estoquista" -> "Catwoman App": Deseja finalizar a apuração das divergências
    "Catwoman App" -> "Catwoman Api": PATCH /v1/organizations/{id}/branches/{id}/countings/{id}
    "Catwoman Api" -> "Darkseid Api": PATCH /v1/organizations/{id}/branches/{id}/countings/{id}
    "Darkseid Api" -> "Catwoman Api": https status 200
    "Catwoman Api" -> "Catwoman App": https status 200
    "Catwoman App" -> "estoquista": Mostra mensagem de sucesso
  end
@enduml