@startuml Fluxo de atualização do pagamento do pedido do usuário
database "delivery-db"
"delivery-api" -> "delivery-db" : PUT /v1/orders/{uuid}/payment
"delivery-db"  -> "delivery-api" : Atualiza o pagamento do pedido [201]
@enduml