@startuml Fluxo de atualização do status do pedido do usuário
database "delivery-db"
"delivery-api" -> "delivery-db" : PUT /v1/orders/{uuid}/status
"delivery-db"  -> "delivery-api" : Atualiza o status do pedido [201]
@enduml