@startuml Fluxo de atualização da avaliação do pedido do usuário
database "delivery-db"
"delivery-api" -> "delivery-db" : PUT /v1/orders/rate/{uuid}
"delivery-db"  -> "delivery-api" : Atualiza a avaliação do pedido [201]
@enduml