@startuml Fluxo criação do grupo de filiais
title Fluxo criação do grupo de filiais
  actor "Admin"
  participant "Aquaman App" #406DD8
  participant "Aquaman Api" #406DD8
  participant "Darkseid Api" #193464
  alt Admin consulta filiais cadastradas
    "Admin" -> "Aquaman App": Abre a tela de consulta
    "Aquaman App" -> "Aquaman Api": GET /v1/organizations/{id}/counting_groups?expand=true     
    "Aquaman Api" -> "Darkseid Api": GET /v1/organizations/{id}/counting_groups?expand=true
    "Darkseid Api" -> "Aquaman Api": http status 200   
    "Aquaman Api" -> "Aquaman App": http status 200
    "Aquaman App" -> "Admin": "exibe grid com as informações"
  end

  alt Admin cadastra filiais cadastradas
    "Admin" -> "Aquaman App": Abre a tela de cadastro
    "Aquaman App" -> "Aquaman Api": POST /v1/organizations/{id}/counting_groups
    "Aquaman Api" -> "Darkseid Api": POST /v1/organizations/{id}/counting_groups
    "Darkseid Api" -> "Aquaman Api": http status 201
    "Aquaman Api" -> "Aquaman App": http status 201
    "Aquaman App" -> "Admin": "exibe informação de sucesso"
  end

  alt Admin deseja inativar grupo de filiais
    "Admin" -> "Aquaman App": Abre a tela de cadastro
    "Aquaman App" -> "Aquaman Api": DELETE /v1/organizations/{id}/counting_groups/{id}    
    "Aquaman Api" -> "Darkseid Api": DELETE /v1/organizations/{id}/counting_groups/{id}
    "Darkseid Api" -> "Aquaman Api": http status 204
    "Aquaman Api" -> "Aquaman App": http status 204
    "Aquaman App" -> "Admin": "exibe alerta informando deleção"
  end

  alt Admin deseja editar grupo de filiais
    "Admin" -> "Aquaman App": Abre a tela de cadastro
    "Aquaman App" -> "Aquaman Api": PATCH /v1/organizations/{id}/counting_groups/{id}    
    "Aquaman Api" -> "Darkseid Api": PATCH /v1/organizations/{id}/counting_groups/{id}
    "Darkseid Api" -> "Aquaman Api": http status 200
    "Aquaman Api" -> "Aquaman App": http status 200
    "Aquaman App" -> "Admin": "exibe informação de sucesso"
  end
@enduml