@startuml Fluxo de bloqueios
title Fluxo de bloqueios
  actor "Admin"
  participant "Aquaman App" #406DD8
  participant "Aquaman Api" #406DD8
  participant "Darkseid Api" #193464
  alt Admin deseja subir a planilha com os dados do bloqueio
    "Admin" -> "Aquaman App": Clica botão de upload da panilha
    "Aquaman App" -> "Aquaman Api": POST /v1/organizations/{id}/branches/blocked_countings         
    "Aquaman Api" -> "Darkseid Api": POST /v1/organizations/{id}/branches/blocked_countings
    note left: Faz o parse dos dados para Excel para json
    "Darkseid Api" -> "Aquaman Api": http status 201
    "Aquaman Api" -> "Aquaman App": http status 201    
    "Aquaman App" -> "Admin": "Exibe informação de upload realizado"
  end

  alt Admin deseja fazer download dos dados de bloqueio
    "Admin" -> "Aquaman App": Abre a tela de cadastro
    "Aquaman App" -> "Aquaman Api": GET /v1/organizations/{id}/branches/blocked_countings         
    "Aquaman Api" -> "Darkseid Api": GET /v1/organizations/{id}/branches/blocked_countings
    "Darkseid Api" -> "Aquaman Api": http status 200
    "Aquaman Api" -> "Aquaman App": http status 200  
    note left: Faz o parse dos dados de JSON para Excel
    "Aquaman App" -> "Admin": "Faz download do excel"
  end  
@enduml